[versions]
minSdk = "29"
compileSdk = "36"
targetSdk = "36"
kotlinTargetJvm = "17"

# Plugins
agp = "8.13.0"
kotlin = "2.2.20"
google-services = "4.4.4"
navigation-safeargs = "2.9.5"
crashlytics-gradle = "3.0.6"
ktlint = "13.1.0"
ksp = "2.2.20-2.0.3"
kotlinCompilerExtensionVersion = "1.5.15"

# Libraries
firebase-bom = "34.5.0"

play-services-location = "21.3.0"
play-services-maps = "19.2.0"
play-services-auth = "21.4.0"
play-services-ads = "24.7.0"
user-messaging-platform = "3.2.0"

androidx-recyclerview = "1.4.0"
androidx-multidex = "2.0.1"
androidx-constraintlayout = "2.2.1"
androidx-swiperefreshlayout = "1.1.0"
androidx-viewpager2 = "1.1.0"
androidx-biometric = "1.1.0"
androidx-splashscreen = "1.0.1"
androidx-core-ktx = "1.17.0"
androidx-fragment-ktx = "1.8.9"
androidx-activity-ktx = "1.11.0"
androidx-collection-ktx = "1.5.0"
androidx-palette-ktx = "1.0.0"
androidx-dynamicanimation-ktx = "1.1.0"
androidx-work-runtime = "2.11.0"
androidx-work-runtime-ktx = "2.11.0"
androidx-localbroadcastmanager = "1.1.0"
androidx-activity-compose = "1.11.0"
androidx-compose-material3-adaptive-navigation-suite = "1.5.0-alpha07"
androidx-compose-material3 = "1.4.0"

glance = "1.1.1"
compose-bom = "2025.10.01"

androidx-lifecycle-extensions = "2.2.0"
androidx-lifecycle = "2.9.4"

androidx-room = "2.8.3"

androidx-navigation = "2.9.5"

material = "1.13.0"

kotlinx-coroutines = "1.10.2"

koin = "4.1.1"
koin-android-ext = "3.0.2"

circleimageview = "3.1.0"
retrofit = "3.0.0"
gson = "2.13.2"
jsr305 = "3.0.2"
okhttp3-logging-interceptor = "5.3.0"
dropbox-core-sdk = "7.0.0"
lib-recur = "0.17.1"
commons-lang3 = "3.19.0"
threetenbp = "1.7.2"
threetenabp = "1.4.7"
colorslider = "2.0.6"
android-calendar-ext = "1.0.4"
lottie = "6.7.0"
photoview = "2.3.0"
sheets = "2.3.1"
coil = "2.7.0"

slf4j-api = "2.0.17"
logback-android = "3.0.0"

google-api-services-calendar = "v3-rev20230406-2.0.0"
google-api-services-tasks = "v1-rev20230401-2.0.0"
google-api-services-drive = "v3-rev20230423-2.0.0"
google-http-client-gson = "2.0.2"
google-api-client-android = "2.8.1"

grpc = "1.76.0"

# Testing
junit = "4.13.2"
mockk = "1.14.6"
robolectric = "4.16"
mockito-core = "5.20.0"
mockito-kotlin = "2.2.0"
logback-classic = "1.5.20"
androidx-test-core = "1.7.0"
androidx-core-testing = "2.2.0"
androidx-test-runner = "1.7.0"
androidx-test-rules = "1.7.0"
androidx-espresso-core = "3.7.0"
androidx-uiautomator = "2.3.0"

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-android = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
koin-android-ext = { group = "io.insert-koin", name = "koin-android-ext", version.ref = "koin-android-ext" }
koin-androidx-workmanager = { group = "io.insert-koin", name = "koin-androidx-workmanager", version.ref = "koin" }
koin-androidx-compose = { group = "io.insert-koin", name = "koin-androidx-compose", version.ref = "koin" }

androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidx-recyclerview" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "androidx-multidex" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "androidx-swiperefreshlayout" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "androidx-viewpager2" }
androidx-biometric = { group = "androidx.biometric", name = "biometric", version.ref = "androidx-biometric" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidx-splashscreen" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidx-fragment-ktx" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidx-activity-ktx" }
androidx-collection-ktx = { group = "androidx.collection", name = "collection-ktx", version.ref = "androidx-collection-ktx" }
androidx-palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "androidx-palette-ktx" }
androidx-dynamicanimation-ktx = { group = "androidx.dynamicanimation", name = "dynamicanimation-ktx", version.ref = "androidx-dynamicanimation-ktx" }

glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance" }
glance-material3 = { group = "androidx.glance", name = "glance-material3", version.ref = "glance" }
glance-preview = { group = "androidx.glance", name = "glance-preview", version.ref = "glance" }
glance-appwidget-preview = { group = "androidx.glance", name = "glance-appwidget-preview", version.ref = "glance" }

androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidx-activity-compose" }

compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-animation-animation = { module = "androidx.compose.animation:animation" }
compose-foundation-foundation = { module = "androidx.compose.foundation:foundation" }
compose-foundation-layout = { module = "androidx.compose.foundation:layout" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-material = { module = "androidx.compose.material:material" }
compose-material-iconsext = { module = "androidx.compose.material:material-icons-extended" }
compose-runtime-runtime = { module = "androidx.compose.runtime:runtime" }
compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
compose-ui-ui = { module = "androidx.compose.ui:ui" }
compose-ui-util = { module = "androidx.compose.ui:util" }
compose-ui-text-google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }

#compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "androidx-compose-material3" }
compose-material3-windowsizeclass = { group = "androidx.compose.material3", name = "material3-window-size-class", version.ref = "androidx-compose-material3" }
compose-material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite", version.ref = "androidx-compose-material3-adaptive-navigation-suite" }

androidx-lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "androidx-lifecycle-extensions" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-common-java8 = { group = "androidx.lifecycle", name = "lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }

androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidx-room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }

androidx-work-runtime = { group = "androidx.work", name = "work-runtime", version.ref = "androidx-work-runtime" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidx-work-runtime-ktx" }

androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidx-navigation" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "androidx-navigation" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidx-navigation" }

androidx-localbroadcastmanager = { group = "androidx.localbroadcastmanager", name = "localbroadcastmanager", version.ref = "androidx-localbroadcastmanager" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
firebase-appcheck = { module = "com.google.firebase:firebase-appcheck" }
firebase-appcheck-playintegrity = { module = "com.google.firebase:firebase-appcheck-playintegrity" }

play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-services-location" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "play-services-maps" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "play-services-auth" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "play-services-ads" }
user-messaging-platform = { group = "com.google.android.ump", name = "user-messaging-platform", version.ref = "user-messaging-platform" }

kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

circleimageview = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleimageview" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
jsr305 = { group = "com.google.code.findbugs", name = "jsr305", version.ref = "jsr305" }
okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3-logging-interceptor" }
dropbox-core-sdk = { group = "com.dropbox.core", name = "dropbox-core-sdk", version.ref = "dropbox-core-sdk" }
dropbox-android-sdk = { group = "com.dropbox.core", name = "dropbox-android-sdk", version.ref = "dropbox-core-sdk" }
lib-recur = { group = "org.dmfs", name = "lib-recur", version.ref = "lib-recur" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
threetenbp = { group = "org.threeten", name = "threetenbp", version.ref = "threetenbp" }
threetenabp = { group = "com.jakewharton.threetenabp", name = "threetenabp", version.ref = "threetenabp" }
colorslider = { group = "com.github.naz013", name = "ColorSlider", version.ref = "colorslider" }
android-calendar-ext = { group = "com.github.naz013", name = "android-calendar-ext", version.ref = "android-calendar-ext" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
photoview = { group = "com.github.chrisbanes", name = "PhotoView", version.ref = "photoview" }
coil = { group = "io.coil-kt", name = "coil", version.ref = "coil" }

sheets-core = { group = "com.maxkeppeler.sheets", name = "core", version.ref = "sheets" }
sheets-lottie = { group = "com.maxkeppeler.sheets", name = "lottie", version.ref = "sheets" }
sheets-input = { group = "com.maxkeppeler.sheets", name = "input", version.ref = "sheets" }
sheets-info = { group = "com.maxkeppeler.sheets", name = "info", version.ref = "sheets" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j-api" }
logback-android = { group = "com.github.tony19", name = "logback-android", version.ref = "logback-android" }

google-api-services-calendar = { group = "com.google.apis", name = "google-api-services-calendar", version.ref = "google-api-services-calendar" }
google-api-services-tasks = { group = "com.google.apis", name = "google-api-services-tasks", version.ref = "google-api-services-tasks" }
google-api-services-drive = { group = "com.google.apis", name = "google-api-services-drive", version.ref = "google-api-services-drive" }
google-http-client-gson = { group = "com.google.http-client", name = "google-http-client-gson", version.ref = "google-http-client-gson" }
google-api-client-android = { group = "com.google.api-client", name = "google-api-client-android", version.ref = "google-api-client-android" }

grpc-okhttp = { group = "io.grpc", name = "grpc-okhttp", version.ref = "grpc" }
grpc-android = { group = "io.grpc", name = "grpc-android", version.ref = "grpc" }

# Testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito-core" }
mockito-kotlin = { group = "com.nhaarman.mockitokotlin2", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidx-test-core" }
androidx-core-testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidx-core-testing" }
androidx-lifecycle-runtime-testing = { group = "androidx.lifecycle", name = "lifecycle-runtime-testing", version.ref = "androidx-lifecycle" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidx-test-rules" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidx-uiautomator" }

kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback-classic" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
java-library = { id = "java-library" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation-safeargs" }
crashlytics-gradle = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics-gradle" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
